### ISSUE TITLE
Could this be updated to retrieve code/image from IronBank instead?

### ISSUE THREAD

**Issue by SebTardif** [rushyrush/rke-federal-up#1]
I wonder if this could be updated to retrieve code/image from IronBank instead, a public repo with certified secure images. Or maybe you know of another similar project doing this?

**Comment by rushyrush** [comment]
@SebTardif that code already exist on [Repo1 ](https://repo1.dso.mil/platform-one/distros/rancher-federal/rke2/rke2-aws-terraform)
